### PR TITLE
Run regression test suite with 3.2.0 official and maintenance

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Add all Pending OSMs, run all tests with 3.2.0 official. I also done a three way comparison between 3.1.0/9.4.0, Transition the 3.1.0 idf to v9.5.0, and 3.2.0/9.5.0

I also uploaded the results to the Google Sheet tracker [here](https://docs.google.com/spreadsheets/d/1gL8KSwRPtMPYj-QrTwlCwHJvNRP7llQyEinfM1-1Usg/edit#gid=1147582096)

I didn't manage to run the bundle git test due to to bundler version mismatch with my ruby.

image

### EDIT: Please see at end of thread for updated numbers/figures, I caught a couple of issues

A few EUI deviations, as expected given that we changed E+ version (and less than usual too):

```
Row threshold = 1.00%, Cell Display Threshold = 0.10%
Max Absolute difference: 15.1163%
```

image

There is really one single test, `unitary_test.rb` that is a bit concerning because it is NOT due to 9.5.0:

image

----

image

----

image

### CODE REVIEW

**Comment by jmarrec** [comment]
**unitary_test.rb**

image


image


---

 More details:

image

image

**Comment by jmarrec** [comment]
Something must have gotten wrong with unitary_test, seems like the wrong IDF from 3.1.0 was copied over or something:

```python
In [1]: len(old_idf.objects(True)), len(transitioned_idf.objects(True)), len(new_idf.objects(True))
Out[1]: (655, 655, 235)
```

**Comment by jmarrec** [comment]
Ok, there was indeed a problem, all good now!


image


Note: **ignore elcd_no_generators** that is expected. This test shouldn't have been ran in this 3-way scenario, that's my fault. (I redid the 3 way comparison like 5 times already and there is a tedious manual step of cleaning up the HTML so I won't do it again just for that)

image

image

**Comment by tijcolem** [comment]
@jmarrec looks good to me.  Glad you were able to figure out the issue with the `unitary_test.`    I really like you are able to compare differences between OS versions w/o E+ influence. That's a super useful diff chart.

**Review by tijcolem — APPROVED** [review]

**Pull request merged**
