### PR TITLE
Run regression test suite with 3.3.0 official and maintenance

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Add all Pending OSMs, run all tests with 3.3.0 official.

* I also uploaded the results to the Google Sheet tracker [here](https://docs.google.com/spreadsheets/d/1gL8KSwRPtMPYj-QrTwlCwHJvNRP7llQyEinfM1-1Usg/edit#gid=1147582096)

* No new failures. <strikethrough>Some slight EUI differences, nothing problematic (it's an E+ bump)</strikethrough> (**Edit: See below for updated numbers and graphs**)

```
Row threshold = 1.00%, Cell Display Threshold = 0.10%
Max Absolute difference: 18.4623%
Max Absolute difference of last version: 18.4623%
```

image

* Run with E+ Space feature turned on as well. Key diffs between the no spaces and with spaces

image

### CODE REVIEW

**Comment by jmarrec** [comment]
The EUI diffs are due to the Parallel runs that I fixed in https://github.com/NREL/OpenStudio-resources/pull/155. The issue is that I need to retroactively run with that fix in older versions. I'll do that for 3.2.0 and 3.2.1 at least.

**Comment by jmarrec** [comment]
After running some problematic (due to parallel error) tests back to 3.0.0 (unfortunately, the rubocop enforces new ruby style, so it definitely doesn't run with ruby 2.2.4, due to syntax like `obj_missing_getters&.include?(getter_name)` which wasn't supported back then). I don't feel like fixing that right now, it doesn't matter much

image

image

**Comment by jmarrec** [comment]
image

**Comment by tijcolem** [comment]
@jmarrec Looks good. I like seeing that there is minor differences in the space feature turned off vs on. This will be useful to keep on eye on this as we move to making the space translation the default behavior.  

And I wouldn't worry about previous runs < 3.0.0 due to the parallel error. If we want to update those metrics we could just run single threaded vs fixing a bunch of syntax issues.

**Review by tijcolem — APPROVED** [review]

**Pull request merged**
