### PR TITLE
Additional Properties

### PR DESCRIPTION
**Pull request by joseph-robertson**

### CODE REVIEW

**Comment by jmarrec** [comment]
@joseph-robertson here are the test results for this test you added:

image

Can I replace the OSM file with the 2.4.3 version?

**Comment by joseph-robertson** [comment]
@jmarrec yes, you can. although what implications does that have? this is supposed to be backward compatible.

**Comment by jmarrec** [comment]
Well the ruby measure and the 2.4.1 osm don't run in 2.4.1.
So if I replace the OSM with the output of the ruby test of 2.4.3 (osm version = 2.4.3 then), I no longer show a failure... In all it means we don't expect this to work in versions before 2.4.3

**Comment by macumber** [comment]
@jmarrec thanks for all this, we typically have this issue when people develop objects over several os versions.  you are right that we want to update the versions to the version where the feature actually got introduced to os.  any ideas on how to enforce that are appreciated

**Comment by jmarrec** [comment]
I’m thinking I want to create a pull request template summarizing the requirements and needed checks if that’s ok, that would include testing stability of the ruby test etc.
(Of course the benefit of this relies on not being short circuited by people with write access). Similar to what energyplus has implemented.

As far as new tests goes, in the future there will be little cases for “missing” tests (meaning a long-added object in the API doesn’t have a test already), and it’ll be more straightforward, but my idea is that the osm test should be added one the first openstudio official release that makes the ruby test pass is out.
For a “missing” one, that means running the ruby test in all past versions using docker, and identifying the first openstudio version that worked. Which is what I’ve been doing so far for dozens of ruby tests that didn’t have matching OSM ones.

 In the pull request template there would be a mention for this, and either:

* if the official release of question is pending, there should be a TODO with the test_xxx_osm in model_tests.rb commented out (which means “someone” is responsible for tracking these...), or,
* perhaps the PR shouldn’t get merged until the osm is added (but that would likely discourage “lambda” users contributing because it’ll drag along, though I’m not sure we’ll get many of those...). This is what I’m leaning towards personally...

Thoughts?

——
Sent from a mobile device, please excuse the brevity.
Julien Marrec, EBCP, BPI MFBA
Owner


Direct: +33 6 95 14 42 13
Website: www.effibem.com

LinkedIn (en) | (fr)

**Pull request merged**
