### PR TITLE
Ems outvar test

### PR DESCRIPTION
**Pull request by brianlball**
test for fix 3336 EMS metered output variable swig issue

### CODE REVIEW

**Comment by jmarrec** [comment]
@brianlball This seems ok to me since it shouldn't change EUI (only output variables).
Did you double check that it runs properly and doesn't produce any EUI difference indeed?

**Comment by brianlball** [comment]
@jmarrec I did not check the EUI since these were output variables, so hopefully that didnt introduce a change.
Are these tests being run on older versions?

**Comment by brianlball** [comment]
@jmarrec added check for OS version

**Comment by jmarrec** [comment]
Your PR was merged already, so I changed the version check to be "> 2.7.0"

**Pull request merged**
