### PR TITLE
Timings ci refactor

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

This is a (major) refactor of #160 

**Changes best viewed before I broke it into two files, so first 3 commits: https://github.com/NREL/OpenStudio-resources/pull/161/files/86d14b4dbef8e279fefb8403264b78db2c45bfc8**

- Encapsulate everything inside a class
- Break it into CLI versus support (so that you can use the perf class in a notebook for eg)
- Setup logging: to console (logging level can be set) and to file (always in DEBUG)
- Setup progress bars for downloads, and nested progress bars for running stuff
- adjust argparse settings
- Support running multiple test files
- Create graphs to match (it's harder to display now that we have an extra dimension...)
- Generate an HTML report that embeds two tables and two graphs
- Downloading and/or extracting only happens if need be, unless you force it (I haven't added a CLI arg for that yet)

example call:

```shell
python performance_test.py \
  --urls https://openstudio-ci-builds.s3-us-west-2.amazonaws.com/develop/OpenStudio-3.3.1-alpha%2Bf3fba80d69-Darwin.tar.gz \
         https://openstudio-ci-builds.s3-us-west-2.amazonaws.com/develop/OpenStudio-3.3.1-alpha%2B44a7660fbb-Darwin.tar.gz \
  --number-runs 2 \
  --test-files baseline_sys01.rb zone_hvac.rb airloop_and_zonehvac.rb
```

### CODE REVIEW

**Comment by tijcolem** [comment]
Thanks @jmarrec. This is a major improvement and is more flexible now with the addition running multiple tests as well. I have the CI already running the current version so I'll just make some adjustments on the CI side to work with the new output and then I'll merge this in.  I think eventually we'll want to make a new directory for perf related test files so we can merge this into develop/master?

**Comment by jmarrec** [comment]
@tijcolem How about we do that on the fly?

Any test files requested: take it from model/simulationtests, copy it in the perf_test folder and add the timings stuff?


Any file is structured like this:

```
[..content...]
model.save(...)
```

So it's easy to add the timings and FT timings to it.

**Comment by tijcolem** [comment]
Sure, if you know a way to dynamically add in the timings on the fly that would be awesome.

**Comment by jmarrec** [comment]
@tijcolem Added it in https://github.com/NREL/OpenStudio-resources/pull/161/commits/2371408eba7d78e3ebaee03bcf42ccf4e428fe48

**Comment by jmarrec** [comment]
@tijcolem I added a notebook I had around where I do VT( load an osm), model.save, FT and workspace.save in https://github.com/NREL/OpenStudio-resources/pull/161/commits/2cb686c294a5fd3ce4c5d63d46e9dd4abe0dcf28

Should we integrate this too?

**Comment by tijcolem** [comment]
@jmarrec Cool, and yes on the notebook. This will be nice for developers to use locally.

**Comment by jmarrec** [comment]
@tijcolem time to merge? This one goes into #160, then we can decide if we're ready to merge #160 into develop

**Comment by tijcolem** [comment]
@jmarrec revisiting this. Yep, I made the changes on CI side. Let's merge.

**Pull request merged**
