### PR TITLE
Zone load distribution scheme

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

**Addresses NREL/OpenStudio#3257.**

Link to relevant GitHub Issue(s) if appropriate:

This Pull Request is concerning:

 - [ ] **Case 1 - `NewTest`:** a new test for a new model API class,
 - [ ] **Case 2 - `TestFix`:** a fix for an existing test. The GitHub issue should be referenced in the PR description
 - [x] **Case 3 - `NewTestForExisting`:** a new test for an already-existing model API class
 - [ ] **Case 4 - `Other`:** Something else, like maintenance of the repo, or just committing test results with a new OpenStudio version.

Depending on your answer, please fill out the required section below, and delete the three others.
Leave the review checklist in place.

**Note**: You can open a specific PR template directly by appending `?template=xxx` argument with the value `newtest.md`, `testfix.md` or `newtestforexisting.md`.

----------------------------------------------------------------------------------------------------------

### Case 3: New test for an already-existing model API class

> This pull request adds missing tests for the following classes:
> *  [ThermalZone](https://github.com/NREL/OpenStudio/blob/equiplist_fix/openstudiocore/src/model/ThermalZone.hpp#L391-L393)
> *  [ZoneHVACEquipmentList](https://github.com/NREL/OpenStudio/blob/equiplist_fix/openstudiocore/src/model/ZoneHVACEquipmentList.hpp#L57-L59)

#### Work Checklist

The following has been checked to ensure compliance with the guidelines:

 - [x] **Test has been run backwards** (see [Instructions for Running Docker](https://github.com/NREL/OpenStudio-resources/blob/develop/doc/Instructions_Docker.md)) for all OpenStudio versions
 - [x] **A Matching OSM test** has been added with the output of the ruby test for the oldest OpenStudio release where it passes (include OpenStudio Version)

 - [x] **Ruby test is stable** in the last OpenStudio version: when run multiple times on the same machine, it produces the same total site kBTU.
    - [x] I ensured that I assign systems/loads/etc in a repeatable manner (eg: if I assign stuff to thermalZones, I do `model.getThermalZones.sort_by{|z| z.name.to_s}.each do ...` so I am sure I put the same ZoneHVAC systems to the same zones regardless of their order)
     - [x] I tested stability using `process_results.py` (see `python process_results.py --help` for usage).
    Please paste the text output or heatmap png generated after running the following commands:
        ```bash
        # Clean up all custom-tagged OSWs
        python process_results.py test-stability clean
        # Run your test 5 times in a row. Replace `testname_rb` (eg `airterminal_fourpipebeam_rb`)
        python process_results.py test-stability run -n testname_rb
        # Check that they all passed
        python process_results.py test-status --tagged
        # Check site kBTU differences
        python process_results.py heatmap --tagged

        ```

----------------------------------------------------------------------------------------------------------

### Review Checklist

 - [x] Code style (indentation, variable names, strip trailing spaces)
 - [x] Functional code review (it has to work!)
 - [x] Matching OSM test has been added or `# TODO` added to `model_tests.rb`
 - [x] Appropriate `out.osw` have been committed
 - [x] Test is stable
 - [x] The appropriate labels have been added to this PR:
   - [x] One of: `NewTest`, `TestFix`, `NewTestForExisting`, `Other`
   - [ ] If `NewTest`: add `PendingOSM` if needed

### CODE REVIEW

**Comment by jmarrec** [comment]
@joseph-robertson There are some problems with this PR:

* You are modifying an existing ruby test to call a method that will be introduced in the next official release. This means this test will no longer be backward compatible, so we couldn't run it in older versions if need be, and that's problematic.
* You are setting the value as ` zone.setLoadDistributionScheme("UniformLoad")`, whereas the default and historical behavior is `SequentialLoad`. This means this should create a deviation in EUI from 2.6.1 to 2.6.2 (or rather 2.7.0, the next official OS version), which is specifically the opposite of what we are testing on this repo: EUI shouldn't change from one version to the next (unless there's an E+ reason behind it)

Worst case scenario this should include a check for the version, and call the method only if the version is superior to 2.6.1, and set it to "SequentialLoad", but I think we shouldn't.

```ruby
if Gem::Version.new(OpenStudio::openStudioVersion) > Gem::Version.new("2.6.1")
    zone.setLoadDistributionScheme("SequentialLoad")
end
```

Here, the matching OSM test will do its job to check that the VersionTranslation code you included is fine, and that the EUI doesn't change with historical behavior.

Instead I think you should just test for setter/getters and correct ForwardTranslation in https://github.com/NREL/OpenStudio/pull/3262. I see you already added a model Gtest for setter/getters, you just need to make a FT test to ensure that whatever value you set does end up in the IDF.

**Comment by joseph-robertson** [comment]
@jmarrec Should we just remove this branch and PR then?

**Comment by macumber** [comment]
I plan to merge the pr into openstudio into 2.6.2.  After that I suggest we clean up this pr rather than remove it.  I think @jmarrec will have bandwidth to do the cleanup after 2.6.2 is released

**Comment by macumber** [comment]
@jmarrec can you take a look at this again?

**Comment by jmarrec** [comment]
So I have a branch (which I didn’t push) where the only thing I did is basically:

If os version >= 2.7.0
Set load distribution to sequential load (default historical behavior)
End

That’s the only thing I can think of doing. Otherwise we change the regression test output, which is specifically what we want to avoid.

I feel pretty strongly about this, if that can help deciding.

——
Sent from a mobile device, please excuse the brevity.
Julien Marrec, EBCP, BPI MFBA
Owner


Direct: +33 6 95 14 42 13
Website: www.effibem.com

LinkedIn (en) | (fr)

**Comment by macumber** [comment]
@jmarrec will implement an alternate test

**Pull request closed without merging**
