### PR TITLE
Use Custom Blocks in Foundation Kiva

### PR DESCRIPTION
**Pull request by joseph-robertson**
https://docs.google.com/document/d/1zu-kOTe3q22X2ukZKKg0vn7_2fvhZpakXeHZ05y1-LA/edit#

### CODE REVIEW

**Comment by jmarrec** [comment]
This should not have been merged as is. It modifies an existing test by adding code that will only run on 2.9.0 and above, making it non backward compatible.

I'm not very familiar with Kiva, so I'm not sure what this actually does and if it's a simple as wrapping it in a `if Version >= 2.9.0` clause. @joseph-robertson ?

**Comment by shorowit** [comment]
Joe’s out of the office but pretty sure the answer is yes, version >= 2.9.0 should suffice. This capability was in Kiva for many E+ releases but we didn’t wrap it until now.

**Comment by jmarrec** [comment]
@shorowit I wasn't clear enough. What I meant is whether we actually expect these custom blocks to produce a different EUI. In which case we should revert to the old test, and add a new foundation_kiva_customblock.rb test that would be only >= 2.9.0

**Comment by shorowit** [comment]
Ah. They are blocks of insulation so I’d be surprised if they didn’t change EUI.

**Comment by jmarrec** [comment]
I'm seeing  a .45% change, well within the margin of errors for a new E+ release, so I wasn't sure.

I've reverted the old tests and moved changes into a new `foundation_kiva_customblocks.rb` test

**Comment by joseph-robertson** [comment]
Good call. Sorry, I didn't think about how these would affect EUI.

**Pull request merged**
