### PR TITLE
add scotts model to test framework for EMS

### PR DESCRIPTION
**Pull request by brianlball**
add spacetype version to compare

### CODE REVIEW

**Comment by macumber** [comment]
@brianlball is this supposed to be merged?

**Comment by jmarrec** [comment]
Hey guys, I have follow-up questions on this if you don't mind:

* @brianlball: is there any chance to get a matching ruby test for this model?
* @macumber: Generally speaking, how strictly should we enforce the policy that all tests must have two versions: a ruby one, and an OSM one?

**Comment by brianlball** [comment]
that might fail from the */blank key value issue with output variable and sensor in E+ 8.9.
I'll look at it tomorrow

**Comment by jmarrec** [comment]
@mbadams thanks for following up. I did mention in the last paragraph that official 8.9.0 doesn’t have that problem

**Pull request merged**
