### PR TITLE
Implement SDD tests

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Add SDD tests (both RT and FT) in relation with https://github.com/NREL/OpenStudio/pull/3412

Link to relevant GitHub Issue(s) if appropriate:

This Pull Request is concerning:

 - [ ] **Case 1 - `NewTest`:** a new test for a new model API class,
 - [ ] **Case 2 - `TestFix`:** a fix for an existing test. The GitHub issue should be referenced in the PR description
 - [ ] **Case 3 - `NewTestForExisting`:** a new test for an already-existing model API class
 - [x] **Case 4 - `Other`:** Something else, like maintenance of the repo, or just committing test results with a new OpenStudio version.

----------------------------------------------------------------------------------------------------------

### Case 4: Other

* Added SDD FT and RT tests inside a SDD_tests.rb file
* Updated README.md with info. Please also see model/sddtests/README.md
* Added highlevel_tests.rb to check that all OSM/RB/XML are actually used + ensuring each model RB test has a matching OSM one
* Moved config/helper stuff into `test_helpers.rb`
* Now `sim_test` will also asserts on the fly that Total site energy (kBtu) didn't vary more than 0.5% compared to previous official run (eg if you run for 2.7.2, it'll compare that with the 2.7.1 official). See README.md changes

----------------------------------------------------------------------------------------------------------

### Review Checklist

 - [ ] Code style (indentation, variable names, strip trailing spaces)
 - [ ] Functional code review (it has to work!)
 - [ ] Matching OSM test has been added or `# TODO` added to `model_tests.rb`
 - [ ] Appropriate `out.osw` have been committed
 - [ ] Test is stable
 - [ ] The appropriate labels have been added to this PR:
   - [ ] One of: `NewTest`, `TestFix`, `NewTestForExisting`, `Other`
   - [ ] If `NewTest`: add `PendingOSM` if needed

### CODE REVIEW

**Comment by macumber** [comment]
@jmarrec should we change this to be a pr to develop?  I dont think this is develop3 specific right?

**Comment by jmarrec** [comment]
@macumber you're probably right in general. Specifically I think it would fail with develop, because in the refactor I caught a few funky things in the SDD FT and RT. I will try with develop and see how bad it is.

**Comment by jmarrec** [comment]
@macumber I merged everything into this branch and cleaned up now that there is a test_helpers.rb etc.
I ran the SDD tests with the 2.8.0 installed too. Changed the base branch to develop.

**Comment by macumber** [comment]
@jmarrec should I merge this for testing with develop?

**Comment by jmarrec** [comment]
@macumber from memory it should mostly work with develop, otherwise it would be manageable to fix issues.
Some tests will fail with develop though since I have caught a few typos during the qxml -> pugixml. I guess it's a matter of trying or having CI try it.
I'll leave it up to you to decide whether we merge now and fix later or try now and merge later.
I can probably find a few hours this week either case

**Pull request merged**
